[package]
name = "grelier"
version = "0.1.0"
edition = "2024"

[dependencies]
swayipc = "3"
iced = { version = "0.14", features = ["image", "svg"] }
iced_layershell = "0.14.2"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
argh = "0.1"